version: 2
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
    groups:
      swift:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-toolchain:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-compose:
        patterns:
          - "*"
