[tasks.iphone]
run = [
    """xcodebuild \
  -project Bleat.xcodeproj \
  -scheme Bleat -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 17 Pro' -derivedDataPath .build/xcode-derived build""",
    """xcrun simctl install booted \
  .build/xcode-derived/Build/Products/Debug-iphonesimulator/Bleat.app build""",
    """xcrun simctl install booted .build/xcode-derived/Build/Products/Debug-iphonesimulator/Bleat.app""",
    """xcrun simctl launch --terminate-running-process booted com.yaleman.Bleat""",
]
