//! Generated API modules
//!
//! This module exports all generated API types and clients.
//! Do not edit manually - regenerate using the appropriate script.
//!
//! Generated by openapi-to-rust v0.17.0. Source OpenAPI document: appstore.json

//! Configured `module_name` = `appstore`. Mount this tree under your
//! preferred path, e.g. `pub mod appstore;` in your crate root.

#![allow(unused_imports)]

pub mod client;
pub mod types;

pub use client::*;
pub use types::*;
